server:
  port: 8080

build.name: @project.name@
build.version: @project.version@

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fiapprojectsevicedb
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: 'none'
    show-sql: true